# Generated by Django 2.2.4 on 2019-08-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eemail',
            field=models.EmailField(max_length=254, verbose_name=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='eid',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(max_length=255),
        ),
    ]
